name: parameterized_test
description: Simple package that helps with executing parameterized tests. Inspired by JUnit ParameterizedTest CsvValues.
version: 0.0.5
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  test: ^1.20.1

dev_dependencies:
  lints: ^1.0.1
