name: parameterized_test
description: Simple package that helps with executing parameterized tests. Inspired by JUnit ParameterizedTest.
version: 1.1.3
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.9.1
  test: ^1.20.0

dev_dependencies:
  lints: ">=2.1.1 <4.0.0"