name: flutter_parameterized_test
description: Simple package that helps with executing parameterized tests. Inspired by JUnit ParameterizedTest.
version: 1.0.0-rc1
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  parameterized_source: ^0.2.1


dev_dependencies:
  lints: ^1.0.1
