name: parameterized_test
description: Simple package that helps with executing parameterized tests. Inspired by JUnit ParameterizedTest CsvValues.
version: 0.2.1
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  parameterized_source: ^0.2.1
  test: ^1.21.4

dev_dependencies:
  lints: ^1.0.1
