name: parameterized_test
description: Simple package that helps with executing parameterized tests. Inspired by JUnit ParameterizedTest CsvValues.
version: 0.2.1
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  # Pin specific version of the test library to also match with flutter_test
  test: 1.23.0

dev_dependencies:
  lints: ^2.0.1
