name: parameterized_test
description: Simple package that helps with executing parameterized tests. Inspired by JUnit ParameterizedTest.
version: 1.0.0-rc1
homepage: https://www.github.com/DutchCodingCompany/parameterized_test

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0
  test: ^1.20.0

dev_dependencies:
  lints: ^2.0.1
  dart_code_metrics: ^5.7.0
